#define VERSION_CODE "0.5.2"

#define PIN_UNUSED_SPEAKER_ALIBI_B 5
#define PIN_UNUSED_SPEAKER_ALIBI_A 12
#define PIN_LED_ST_CP 13
#define PIN_LED_SH_CP 14
#define PIN_MOTOR_A 16
#define PIN_MOTOR_B 17
#define PIN_LED_BACK_CENTER 18
#define PIN_REVERSE 19
#define PIN_SPEAKER 25
#define PIN_LED_EN 26
#define PIN_LED_DS 27
#define PIN_PUSH_BUTTON 34
#define PIN_COLOR_SENSOR_LED 4
//#define PIN_COLOR_SENSOR_INTERRUPT 36
#define PIN_MAGNET_SENSOR_RIGHT 32
#define PIN_MAGNET_SENSOR_LEFT 33

#define DEFAULT_WIFI_SSID "Kosmische Hintergrundstrahlung"
#define DEFAULT_WIFI_PASSWORD "sheldoncooper"
#define DEFAULT_WIFI_HOSTNAME "Baureihe 101-04" // The ESP32 Hostname string is allowed to have only letters, numbers, and the dash symbol!!

#define WIFI_CHECK_INTERVAL 200
#define WIFI_INITIAL_CONNECTING_TIME 2500
#define WIFI_RETRY_INTERVAL 10000
#define WIFI_CONNECTION_MAXIMUM_RETRY 5
#define OTA_CHECK_INTERVAL 500

#define LOGGING_SERVER_IP "192.168.10.29"
#define LOGGING_SERVER_PORT "8032"

#define SERIAL_BAUD_RATE 115200

#define SPEED_STEPS 5
