#define VERSION_CODE "0.5.0"

#define DEFAULT_WIFI_SSID "Kosmische Hintergrundstrahlung"
#define DEFAULT_WIFI_PASSWORD "sheldoncooper"
#define DEFAULT_WIFI_HOSTNAME "Baureihe 101.01"
#define WIFI_CHECK_INTERVAL 200
#define WIFI_RETRY_INTERVAL 30000
#define LOGGING_SERVER_IP "192.168.10.29"
#define LOGGING_SERVER_PORT "8032"
#define SERIAL_BAUD_RATE 115200

#define WIFI_CONNECTION_MAXIMUM_RETRY 5

#define PIN_MOTOR_A 16
#define PIN_MOTOR_B 17
#define PIN_PUSH_BUTTON 18
#define PIN_REVERSE 19
#define SPEED_STEPS 5